### ISSUE TITLE
[Feature Request] Test logging / sharing

### ISSUE THREAD

**Issue by millercentral** [openspeedtest/Speed-Test#10]
It would be great to be able to log all test runs (client ip, client geoloc, download, upload, jitter, ping) in a datasource (ie mysql), and ideally also provide a durable URL that users can use to share a result they got running the tool with others.

**Comment by openspeedtest** [comment]
Already we have this option 

Edit Index.html 

var saveData = true;
var saveDataURL = "//yourDatabase.Server.com:4500/save?data=";

You need a PHP/MySQL, Node.JS or any other backend 

From the post request you can get the client IP and read the data from the URL.

Put it in to a database. 

client geoloc can be get from the ipaddress using some ip api 

" durable URL that users can use to share a result they got running the tool with others."

After test if you click the application UI , it will take you to 

this page 

https://openspeedtest.com/results/show.php?&d=104.02&u=103.92&dd=143.64&ud=144.37&p=0.4&j=0

Client can Email this page to support staff or keep it for future ref. 

Another option 

if you use SelfHosted iframe you can 
http://openspeedtest.com/admin
view the results from our database 

Fully self hosted, docker image with MySQL or any other database and a dashboard to view all test results is in my todo list. and will work on this later.  

But most likely it will be a separate docker image or tag 

because most people don't need a database, so why we need to waste resources.
