### ISSUE TITLE
[Question] - NPM performance

### ISSUE THREAD

**Issue by ma-karai** [openspeedtest/Speed-Test#19]
You posted a video on the nginx proxy manager comparing native SSL with NPM ssl, and showed differences in max speeds. 

Did you find settings in the advanced section to tune these findings?

**Comment by openspeedtest** [comment]
I am not that good in Linux Server Administration,[ Posted this](https://community.traefik.io/t/very-bad-upload-speed-when-using-traefik-with-tsl-ssl/15082/3) in traefik forums, but didn't got any answers. Same for NPM. Maybe due to bad configuration or consumer grade hardware used, like pi and 3900XT.  now i am busy with some other works. After sometime i am planning to learn more "Linux" Stuff. Then i will write a documentation.
