### ISSUE TITLE
[Feature Request] Show details about result directly below results screen

### ISSUE THREAD

**Issue by ericswpark** [openspeedtest/Speed-Test#29]
Instead of redirecting to the OST website with the detailed results as URL parameters, we could have them show up under the results page so it's accessible with a simple scroll. Details like connection stability, download/upload data usage, etc.

**Comment by openspeedtest** [comment]
That is an important feature. Email the result page to an IT Professional for troubleshooting connectivity issues. 
So they can see the speed, jitter & ping along with transferred data. So you can find and fix issues by analyzing those values on the result page. Even if you are offline, you can copy the link and view it online later.

**Comment by ericswpark** [comment]
Well then could we have it so that it shows the results *and* a URL that the user can copy and email?

**Comment by openspeedtest** [comment]
Yes, we can do this in different ways. I chose the easiest and most flexible way. Because I don't want to add more UI elements or event handling to SelfHosted version. Now I use the same script everywhere. The main website, Widget, SelfHosted Widget, SelfHosted Offline Apps (Docker, Windows, Mac, Linux, iOS, Android etc.)
