### ISSUE TITLE
Continue the latency measurements while up/downloads are running

### ISSUE THREAD

**Issue by SteveBox0** [openspeedtest/Speed-Test#33]
Having another test that also measures latency and jitter while the download and upload tests are running would be handy. This will help measure bufferbloat, etc.

**Comment by openspeedtest** [comment]
Watch it https://youtu.be/104T5MvJBCc run
t=d&s=y&r to run download test for a full year. 
t=u&s=y&r to run upload test for a full year. 
t=p&p=1000000 to send 1L ping to server. 
Run in 3 different windows if you run it at the same time. Also you can use 3 different browsers or devices.

**Comment by SteveBox0** [comment]
Yes, it possible to run them via multiple sessions at the same time but ideally it should be part of a single speed test UI fast.com or 
https://www.waveform.com/tools/bufferbloat .

**Comment by openspeedtest** [comment]
We are using XHR. 6 Parallel requests is a limit set by the browser vendors.
We cannot cross that limit by default. 
I think with HTTP3. We can do something like this.
I will keep this idea for the Next major update.

**Comment by SteveBox0** [comment]
Fast.com keep within the 6 concurrent request limit and track the "loaded" latency as well. Might be worth having a look into how its able to do it. 

At least from a quick look at the F12 network tab, i dont see dedicated http requests for ping/latency.

**Comment by openspeedtest** [comment]
We are using all six threads on capable devices and connections. if we try to test latency with the additional requests it will block the overall test progress by the amount of latency of the user connection. but one thing we can do is to measure the XHR send event and Load event time for all requests, Then we can report latency under load. I don't know the accuracy of those results because the browser may block XHR requests to preserve the device's battery life, CPU and RAM, etc. I will test this on the next major update and if possible I will add this.
