### ISSUE TITLE
Measure Multiple sizes and extend 

### ISSUE THREAD

**Issue by SteveBox0** [openspeedtest/Speed-Test#34]
Would it be possible to have an extended version that test different sizes for the download and upload test? Ideally with similar results to the below site. 

https://speed.cloudflare.com/

**Comment by openspeedtest** [comment]
You can do more than that https://youtu.be/104T5MvJBCc watch it. 
You need to use our docker container or openspeedtest server. 
This is not exactly like cloudflare test. I feel like it's pointless. We can run download, upload and ping for unlimited amount of time. If you need to view it at the same time run it in 3 different windows or browser.

**Comment by SteveBox0** [comment]
Based on a quick look at the video i cant see any URL parm for payload size.

Also, Cloudflare speed test does not run the tests at the same time but instead one after each other. Reducing the number of test runs as the payload get larger as per the attached screenshot.
![image](https://user-images.githubusercontent.com/86661487/189834859-37e3a124-80ab-41c1-8edb-6bee9b4f849a.png)

It also provide detailed data for each test run.
![image](https://user-images.githubusercontent.com/86661487/189835526-1d70ae91-c84b-4da3-91e0-60deafe5741e.png)

**Comment by openspeedtest** [comment]
That is a different algorithm to find network speed, like 'speedofme'
I feel like the OpenSpeedTest algorithm is better. Because it will use less memory and efficiently saturate the available bandwidth. On an M1 MacMini, I can test 20 to 25Gbps with this script. Then why should I look at a different algorithm? 
What are the benefits we will get if we adopt a similar algorithm?

**Comment by openspeedtest** [comment]
I used a similar[ algorithm in 2013](https://github.com/openw3/Open-Source-Internet-Speed-Test--Broadband-bandwidth-test), found it less efficient in 2014, and moved to this algorithm in 2014 itself.

**Comment by SteveBox0** [comment]
I dont think i am asking for a different algorithm as i can replicate the tests for each size manually by editing the "downloading" file to match the required size.

The reason i am after the different sizes is understanding the performance for different web apps/use cases. E.g. For example your own site (https://openspeedtest.com/) has an average of 12kB per http request. While a video stream will be much larger per request. This is why Cloudflare speed test includes the different sizes until it maxes out your connection.

**Comment by openspeedtest** [comment]
This project's scope is to show the available bandwidth, run a stress test, ping, and jitter. So you can easily identify a bad connection or equipment after a quick test, which is under 30 seconds. As you said, we can easily implement a feature like that by adding more static files like 100kb, 10Mb, etc. They need a unique-looking tool. That is why they show all kinds of information they can. However, I still feel like it's pointless. Because if you have a 100Mbps connection with 10 Ms ping and 1 Ms. Jitter, Then you need to know how it behaves under 100Kb. 10Mb? The answer is the same if the latency and ping remain the same. Ping and jitter will not remain the same for LTE and 3G connections. So, each test will show slightly different results. You can see the same information just by looking at the jitter value. An unstable connection jitter value will be above 2 or 3 digits. I am planning to add more dedicated tests on separate pages like VOIP simulation, game simulation, etc in the future. So at that time, we can add a test like this.
