### ISSUE TITLE
[Feature Request] Site branding customization

### ISSUE THREAD

**Issue by millercentral** [openspeedtest/Speed-Test#9]
Really like OpenSpeedTest, thanks for the work on this. It would be great if we could add site information to the page about the hosting site. Docker environment variables or a config file would be ideal. For example:

- Ability to change page title from "Speed Test OpenSpeedtest.com" to something custom, for example "mydomain.com Speed Test by OpenSpeedTest.com"
- An optional additional box (next to or below the ping/jitter box) that indicates server "name" (env/config provided) and geographic location (City, State, or City, Country), and maybe ip address
- An option to replace the pre-run logo on the speedometer

**Comment by openspeedtest** [comment]
1) Use bind mounts
and edit index.html 

2) Whole UI is an SVG. Instead of adding it there you can have the server name, icon or support information in the HTML body itself.  
for Example 
http://speedtest.mst.edu/ 
They use iframe, but you can change index.html page like this in docker.

3) If you really need to remove the logo , i think you can remove it from Index.html. Also you can put your own logo. But it should be an SVG.

You can do all of this things right now, all you need to do is edit index.html 

But it is not the easy way to accomplish the task. 

I added this request to my to do list and will address this issues on the next update. 

currently i shifted focus to other projects, 2.5 was a major release and i was working on that from dec. 

So it will take some time for me to came back to "Speed Test" script.

So for now, you do it yourself by editing index.html. 

Keep an eye on this project. Once i push the update you can do it that way. It will take several months for sure. 

I need to finish few other projects.

Thanks

**Comment by mckaygerhard** [comment]
the commits since feb 17 does nto referes this issue.. any hint?

**Comment by openspeedtest** [comment]
Edit index.html yourself and mount it or build your own image.  That is the better solution.  Because people may want many custom changes or behaviours.

**Comment by mckaygerhard** [comment]
i can document a way and populate the wiki about how to do it.. but next time dont close the issues cos are not resolved.. i will try to made a kind of page for that
