### ISSUE TITLE
Speed when runing in Docker

### ISSUE THREAD

**Issue by jacko306** [openspeedtest/Speed-Test#95]
I have just installed openspeedtest but only get around 25mb to 30mb when testing both from the internal network and the internet even though I'm running 1gig on internal and have a 450mb internet connrction. I'm running docker on a Synology NAS and don't see memory or CPU issues, I've also read about using the host network adapter rather than the bridge but that doesn't seem to make a difference.    It's a stand install with ports changed and running on HTTP or HTTPS doesn't seem to make any difference.   I know the speed to the NAS is good as I've tested with a simple website and don't see any performance issues.  Is there any think in docker that could be restricting performance or have I missed something?

**Comment by jacko306** [comment]
Just tested with the Android openspeddtest on my phone and that works reporting the correct wifi speeds so this has to be something to do with running it on docker or a Synology NAS.

**Comment by openspeedtest** [comment]
Maybe bad cables? 
Did you install the speed test like this 
https://github.com/openspeedtest/Speed-Test/issues/94#issuecomment-1702042914
You can choose any port. In this video i choose 90 for http and 91 for https.

**Comment by jacko306** [comment]
Can't be a bad cable as I get the full 1GB when copying files to and from the NAS also the simple website worked at 1GB so has to be something to do with docker or openspeedtest?. Installed as per the video but used port 3000 and 3001

**Comment by openspeedtest** [comment]
Are you experiencing slow speeds when accessing your NAS SpeedTest  from your phone? 

If so, try installing the OpenSpeedTest Server on your laptop and test the WiFi speed while connected to the same Ethernet cable that is currently connected to your NAS.

If the speed test results are correct, then the NAS is the problem.  Because cables, router etc working fine. 

I have never faced an issue like this with my Synology NAS or Docker. However, you may want to try removing the container and installing it again.

**Comment by jacko306** [comment]
Speed when testing from another device is the same 25 to 30MB. If I install opensoeddtest on my PC all is fine I get around 1GB locally and 450mb via internet connection so it's a docker or opensoeddtest issue as NAS throughput is also fine via SMB or via a simple website.

**Comment by jacko306** [comment]
I have found the issue for some reason if I run it on port 90 and 91 it works.
